CREATE TABLE IF NOT EXISTS roles
(
  id int(11) NOT NULL AUTO_INCREMENT,
  role varchar(250) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
